example.property: "I AM IN THE DEV"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/microservicesdev?serverTimezone=UTC"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}ab8e4d8efce86db68f94d34696f6aa4d257cea3b48c086c3fd0804385e33cccd"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.org.hibernate.dialect.MySQL5Dialect"
